/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_gocoding_common_Bizlayer */

#ifndef _Included_cn_gocoding_common_Bizlayer
#define _Included_cn_gocoding_common_Bizlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_gocoding_common_Bizlayer
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lcn/gocoding/common/JniCallback;)V
 */
JNIEXPORT void JNICALL Java_cn_gocoding_common_Bizlayer_init
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     cn_gocoding_common_Bizlayer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_gocoding_common_Bizlayer_stop
  (JNIEnv *, jclass);

/*
 * Class:     cn_gocoding_common_Bizlayer
 * Method:    call
 * Signature: (Ljava/lang/String;Ljava/lang/String)V
 */
JNIEXPORT void JNICALL Java_cn_gocoding_common_Bizlayer_call
  (JNIEnv *, jclass, jstring, jstring, jboolean);

/*
 * Class:     cn_gocoding_common_Bizlayer
 * Method:    logi
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_gocoding_common_Bizlayer_logi
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_gocoding_common_Bizlayer
 * Method:    logw
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_gocoding_common_Bizlayer_logw
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_gocoding_common_Bizlayer
 * Method:    loge
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_gocoding_common_Bizlayer_loge
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
